name: CompassBar
version: 1.1
main: Enes5519\CompassBar\CompassBar
api: 3.0.5
author: Enes5519

commands:
  compass:
    description: Show compass on bossbar
    permission: compassbar
    overloads: []

permissions:
  compassbar:
    default: true