name: CompassBar
version: 1.0
main: Enes5519\CompassBar\CompassBar
api: 3.0.1
author: Enes5519

commands:
  compass:
    description: Show compass on bossbar
    overloads:
      def:
        parameters: []